#!/bin/sh

# Prevent recursive calls using an environment variable
[ "$HUSKY_SKIP" = "1" ] && exit 0

# Bump patch version in package.json
npm version patch --no-git-tag-version

# Amend the current commit with the version bump
git add package.json
HUSKY_SKIP=1 git commit --amend --no-edit --no-verify


